# Generated by Django 5.0.7 on 2024-08-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategoris',
        ),
    ]
