# Generated by Django 5.0.7 on 2024-08-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_tokenblacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenBlacklist',
        ),
    ]
